---
format: html
---

::: {style="text-align: center;"}
# Michael Willox

**Senior Research Economist \| Statistics Canada, Ottawa, Canada**\
[Michael.Willox@statcan.gc.ca](mailto:Michael.Willox@statcan.gc.ca)\

**Doctoral Researcher \| Brunel University, London, UK**\
[Michael.Willox@brunel.ac.uk](mailto:Michael.Willox\@brunel.ac.uk)\

[LinkedIn](https://www.linkedin.com/in/michael-willox) \| [GitHub](https://github.com/MichaelWillox) \| [Google Scholar](https://scholar.google.com/citations?user=ufTAM-AAAAAJ&hl=en) \| [ORCID](https://orcid.org/my-orcid?orcid=0000-0003-2738-5994) \| [RePEc](https://authors.repec.org/pro/pwi388/)
:::

------------------------------------------------------------------------

## Work Experience

### Senior Research Economist

**Statistics Canada, Ottawa, Canada**

*Dec 2013 – Present*

-   Conducts research on economic and environmental issues to support Statistics Canada’s research agenda.

-   Performs impact evaluations for federal government departments.

-   Manages projects with multidisciplinary teams on a variety of projects such as building and maintaining a world-class economic and environmental database.

-   Built and maintains an online productivity benchmarking tool for Canadian businesses.

-   Developed data series for the Canadian System of National Accounts to support policy development.

### Senior Economist

**Finance Canada, Ottawa, Canada**

*Nov 2006 – Dec 2013*

-   Contributed to the development and coordination of the Federal Government of Canada’s annual Budgets and Economic Updates.

-   Conducted economic analysis on productivity, competition, and labor markets.

-   Provided analysis and briefings on U.S. monetary policy and global economic events.

### Economist

**Environment and Climate Change Canada, Ottawa, Canada**

*Jul 2005 – Nov 2006*

-   Conducted policy research and developed Greenhouse Gas (GHG) and clean air emissions forecasts using the Energy 2020 model.

-   Coordinated briefing materials for senior management.

### Economist

**Natural Resources Canada, Ottawa, Canada**

*Dec 2003 – Jun 2005*

-   Conducted policy research on economic and financial issues facing Canada’s energy sector.

-   Developed responses to public inquiries on behalf of the Minister.

### Program Evaluation Analyst

**Health Canada Departmental Program Evaluation Division, Ottawa, Canada**

*Jun 2002 – Nov 2003*

-   Lead analyst for the evaluation of the Primary Health Care Transition Fund and Alcohol and Drug Rehabilitation Program.

-   Prepared Treasury Board Submissions.

## Education

-   **PhD candidate in Economics and Finance**, Brunel University London, London, UK (Oct 2023 – Present)

-   **Canadian Securities Course**, Canadian Securities Institute, Ottawa, Canada (Oct 2004)

-   **MA in Economics**, McGill University, Montréal, Canada (Apr 2003)

-   **BA (Hons) in Economics**, University of Regina, Regina, Canada (Oct 1996)

-   **BA in Political Science**, University of Regina, Regina, Canada (Apr 1994)

## Computer Skills

-   Office Productivity: Word, Excel, Outlook, PowerPoint

-   Statistical Software: R, R Studio, Shiny, SAS, Stata, Git, GitHub, GitLab, Python

## Publications

Gu, W., & Willox, M. (2023). The Post-2001 Productivity Growth Divergence between Canada and the United States. *International Productivity Monitor*, *45*, 27-60. [Link](http://csls.ca/ipm/45/IPM_45_Gu.pdf).

Kumbhakar, S. C., Badunenko, O., & Willox, M. (2022). Do carbon taxes affect economic and environmental efficiency? The case of British Columbia’s manufacturing plants. *Energy Economics*, *115*, 106359. [Link](https://doi.org/10.1016/j.eneco.2022.106359).

Liu, Huju, Lu, Y., & Willox, M. (2021). "Use of the Canada Emergency Wage Subsidy program by employer businesses in 2020." Ottawa: Statistics Canada, Economic and Social Reports, Catalogue Number 36-28-0001. [Link](https://doi.org/10.25318/36280001202100600006-eng).

Lafrance-Cooke , A. , Macdonald, R., & Willox, M. (2020). "Monthly Business Openings and Closures: Experimental Series for Canada, the Provinces and Territories, and Census Metropolitan Areas.” Economic Insights, No. 116. Statistics Canada Cat. No. 11-626-X. [Link](https://www150.statcan.gc.ca/n1/pub/11-626-x/11-626-x2020014-eng.htm).

Gu, W., Hussain, J., & Willox, M. (2019). *Environmentally adjusted multifactor productivity growth for the Canadian manufacturing sector*. Statistics Canada. [Link](https://www150.statcan.gc.ca/n1/pub/11f0019m/11f0019m2019013-eng.htm).

Gu, W., & Willox, M. (2018). Productivity Growth in Canada and the United States: Recent Industry Trends and Potential Explanations. *International Productivity Monitor*, *35*, 73-94. [Link](https://www.csls.ca/ipm/35/Gu-Willox.pdf).

Baldwin, J. R., & Willox, M. (2016). The industry origins of Canada's weaker labour productivity performance and the role of structural adjustment in the post-2000 period. *International Productivity Monitor, (31), 19-37.* [Link](https://www.csls.ca/ipm/31/baldwin.pdf).

## Awards

-   Statistics Canada Award of Excellence: Outstanding Contribution Award, 2020. Presented for analysis and modeling the demand and supply of personal protective equipment (PPE) across Canada by sector and region during the COVID-19 Pandemic.

-   Statistics Canada Award of Excellence: Excellence in Project Delivery, 2017. Presented for developing the first ever online small business productivity benchmarking tool for the Business Development Bank of Canada (BDC) allowing small businesses to measure their productivity relative to their peers in the same industry.
     

