---
title: "Research"
format:
  html:
    theme: flatly
---

<script>
document.addEventListener('DOMContentLoaded', function() {
  document.body.style.backgroundColor = '#f0f8ff';
});
</script>


### Selected Work

------------------------------------------------------------------------

Gu, Wulong, and Michael Willox. (2023). [The Post-2001 Productivity Growth Divergence between Canada and the United States](http://csls.ca/ipm/45/IPM_45_Gu.pdf). International Productivity Monitor, (45), 28-60.

Abstract: The high degree of integration between the Canadian and the US economies promotes sharing of technologies and innovation spillovers that are conducive to long-term productivity growth convergence. However, since 2001 labour productivity growth rates have diverged in sharp contrast to the previous four decades. A comparison of labour productivity growth decomposed into contributions by industry for both countries reveals that the information and cultural services industry has played an outsized role in the divergence, the start of which coincides with the dot-com recession of the early 2000s. Limits on foreign investment, most notably but not exclusively related to telecommunications, and strong output price growth relative to the United States are key factors for undertaking a simple counterfactual analysis to evaluate the role of competitive intensity in the information and cultural services industry. Estimates of markups and their impact on labour productivity growth suggest that limited competition has significantly reduced the productivity performance of that industry as well as the performances of others that are dependent on its services as intermediate inputs.

Kumbhakar, Subal C., Oleg Badunenko and Michael Willox. (2022). [Do carbon taxes affect economic and environmental efficiency? The case of British Columbia's manufacturing plants](https://doi.org/10.1016/j.eneco.2022.106359). Energy Economics 115: 106359. Ungated: <https://mpra.ub.uni-muenchen.de/118907/1/MPRA_paper_118907.pdf>

Abstract: This paper evaluates the impact of British Columbia’s carbon tax on manufacturers’ economic and environmental performance in a unified modeling framework that allows for a critical distinction between efficiency, technical change, and total factor productivity as performance measures. In contrast to most papers that examine environmental policy impacts on either the economy or the environment, our approach combines a by-production model within a stochastic frontier framework to evaluate the tax’s impacts on both economic and environmental efficiency. Our findings suggest that a 1.0% increase in the carbon tax improved manufacturers’ efficiency in producing desirable output (real sales of manufactured goods) by 0.5%. In addition, the same 1.0% increase in the carbon tax improved manufacturers’ environmental efficiency for greenhouse gas (GHGs) and carbon monoxide (CO) emissions by the same amount, 0.2%. However, the carbon tax led to lower environmental efficiency for emissions of nitrogen oxides (NO~X~), −0.3%. In addition, our use of a rich plant-level dataset reveals considerable heterogeneity in manufacturers’ efficiency responses to the tax. Finally, we suggest that lower efficiency levels for undesirable outputs than desirable outputs indicate that the relative cost of adjusting production processes to improve efficiency favors economic efficiency over environmental efficiency.

Lafrance-Cooke, Amelie, Ryan Macdonald and Michael Willox. (2020). [Monthly Business Openings and Closures: Experimental Series for Canada, the Provinces and Territories, and Census Metropolitan Areas](https://www150.statcan.gc.ca/n1/pub/11-626-x/11-626-x2020014-eng.htm). Economic Insights, Statistics Canada Catalogue no. 11-626-x. Statistics Canada.

Abstract: This article in the Economic Insights series presents monthly estimates of the number of business openings and closing, continuing businesses, and active businesses from January 2015 to April 2020. The estimates for businesses with employees are available for Canada, the provinces and territories, and census metropolitan areas. Where possible, industry information based on two-digit North American Industry Classification Systems codes are also presented. A business closing is defined as a firm that had employment in the previous month, but no employment in the current month. The closure may be temporary or permanent. Since January 2015, an average of approximately 39,000 businesses have closed each month in the Canadian business sector. More than twice that number, 88,187, was observed in April 2020.

Gu, Wulong, Hussain Jakir and Michael Willox. (2019). [Environmentally Adjusted Multifactor Productivity Growth for the Canadian Manufacturing Sector](https://www150.statcan.gc.ca/n1/pub/11f0019m/11f0019m2019013-eng.htm). Analytical Studies Branch Research Paper Series, Statistics Canada Catalogue no. 11f0019m. Statistics Canada.

Abstract: The need to measure both the desirable outputs (goods and services) and the undesirable outputs (emissions of greenhouse gases \[GHGs\] and criteria air contaminants \[CACs\]) from economic activity is becoming increasingly important as economic performance and environmental performance become ever more intertwined. Standard measures of multifactor productivity (MFP) growth provide insights into rising standards of living and the performance of economies, but they may be misleading if only desirable outputs are considered. This study presents estimates of environmentally adjusted multifactor productivity (EAMFP) growth using a new comprehensive database. This database contains information on GHG and CAC emissions, as well as on the production activities of Canadian manufacturers. Overall, the results indicate that EAMFP growth was higher than MFP growth, largely reflecting declines in the undesirable output emissions intensity, in the manufacturing sector from 2004 to 2012.

Gu, Wulong, and Michael Willox. (2018). [Productivity Growth in Canada and the United States: Recent Industry Trends and Potential Explanations](http://www.csls.ca/ipm/35/Gu-Willox.pdf). International Productivity Monitor, (35), 73-94.

Abstract: Labour productivity growth in Canada was weaker than that in the United States from the mid-1980s to 2010, leading to a decline in Canada’s relative productivity level. This situation was mainly due to the lower multifactor productivity (MFP) growth experienced in most Canadian industries in that period. After 2010, however, the pattern reversed itself as labour productivity growth in Canada exceeded that of the United States. Higher labour productivity growth in Canada for the 2010-2014 period was due to a relatively larger capital deepening eﬀect and relatively higher MFP growth. Both these developments were associated with stronger output growth and stronger demand in Canada. In addition, the contributions of ICT producing and ICT intensive using industries to U.S. labour productivity growth waned after 2010. For Canada, ICT producing industries contributed little to overall labour productivity before and after 2010, while ICT intensive using industries exhibited stronger productivity growth after 2010. The latter may reﬂect the more moderate ICT investment in Canada compared to the United States in the 1990s and early 2000s and the more gradual realization of beneﬁts of ICT usage.

Baldwin, J. R., and Michael Willox. (2016). [The Industry Origins of Canada's Weaker Labour Productivity Performance and the Role of Structural Adjustment in the Post-2000 Period](http://www.csls.ca/ipm/31/baldwin.pdf). International Productivity Monitor, (31), 19-36.

Abstract: This article examines how much of the slowdown in labour productivity growth observed in Canada's business sector after 2000 was due to weaker productivity growth within industries and how much was due to structural adjustment. The analysis makes use of a decomposition method that differs from many of the standard decomposition approaches commonly found in the literature and allows for the contributions of changes in the importance of individual industries to be calculated. The approach reveals that the post-2000 slowdown was attributable entirely to weaker productivity growth within industries and that structural adjustment had a slight mitigating effect on the slowdown. Lower productivity growth within three industries - manufacturing; finance, insurance and real estate; and mining, oil and gas - accounted for all of the slowdown in business sector labour productivity growth in the 2000s.
